version: '3.8'

services:
  # app:
  #   container_name: app
  #   build:
  #     context: ./app
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"

    server:
      container_name: server
      build:
        context: ./server
      restart: unless-stopped
      ports:
        - "3000:3000"
    

