version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}

  server:
    container_name: server
    build:
      context: ./server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
